module.exports=(sequelize,dataTypes)=>{
    const User=sequelize.define(
        "User",
        {
            id:{
                type:dataTypes.INTEGER,
                primaryKey:true,
                autoIncrement:true
            },
            name:{
                type:dataTypes.STRING,
                allowNull:false
            },
            price:{
                type:dataTypes.DECIMAL,
                allowNull:false
            },
            discount:{
                type:dataTypes.DECIMAL,
                defaultValue:0
            },
            rol_id:{
                type:dataTypes.STRING,
                allowNull:false
            },
            img:{
                type:dataTypes.STRING,
                allowNull:false
            },
            rating:{
                type:dataTypes.INTEGER(11),
                allowNull:false
            },
            description:{
                type:dataTypes.TEXT
            },
            birthdate:{
                type:dataTypes.DATE
            },
            avatar:{
                type:dataTypes.STRING
            }
        },
        {
            tableName:"users",
            timestamps:false
        }
    )
    User.associate=function(modelos){
        User.belongsTo(modelos.Rol,{
            as:'rol',
            foreignKey:'category_id'
        }),
        User.hasOne(modelos.Carrito,{
            as:'carrito',
            foreignKey:'user_id'
        })
    }
    return User
}