module.exports=(sequelize,dataTypes)=>{
    const User=sequelize.define(
        "User",
        {
            id:{
                type:dataTypes.INTEGER(11),
                primaryKey:true,
                autoIncrement:true
            },
            firstName:{
                type:dataTypes.STRING,
                allowNull:false
            },
            lastName:{
                type:dataTypes.STRING,
                allowNull:false
            },
            username:{
                type:dataTypes.STRING,
                allowNull:false
            },
            email:{
                type:dataTypes.STRING,
                allowNull:false
            },
            password:{
                type:dataTypes.INTEGER(255),
                allowNull:false
            },
            rol_id:{
                type:dataTypes.STRING,
                allowNull:false
            },
            birthdate:{
                type:dataTypes.DATE,
                allowNull:false
            },
            avatar:{
                type:dataTypes.STRING
            }
        },
        {
            tableName:"users",
            timestamps:false
        }
    )
    User.associate=function(modelos){
        User.belongsTo(modelos.Rol,{
            as:'rol',
            foreignKey:'category_id'
        }),
        User.hasOne(modelos.Carrito,{
            as:'carrito',
            foreignKey:'user_id'
        })
    }
    return User
}